"""add_condition_maps_conditions_refactor_cases_runs

Revision ID: 4a08074381f4
Revises: 0e04df3b508e
Create Date: 2026-04-09 23:21:54.159686

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4a08074381f4'
down_revision: Union[str, Sequence[str], None] = '0e04df3b508e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # New tables: condition_maps and conditions
    op.create_table('condition_maps',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_by', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('conditions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('map_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('inflow_velocity', sa.Float(), nullable=False),
    sa.Column('yaw_angle', sa.Float(), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['map_id'], ['condition_maps.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conditions_map_id'), 'conditions', ['map_id'], unique=False)

    # Drop old configurations table (data loss is acceptable — new architecture)
    op.drop_index(op.f('ix_configurations_case_id'), table_name='configurations')
    op.drop_table('configurations')

    # Drop runs table too (it had FK to configurations) then recreate with condition_id
    op.drop_table('runs')
    op.create_table('runs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('case_id', sa.String(length=36), nullable=False),
    sa.Column('condition_id', sa.String(length=36), nullable=True),
    sa.Column('xml_path', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('scheduler_job_id', sa.String(length=255), nullable=True),
    sa.Column('created_by', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.ForeignKeyConstraint(['condition_id'], ['conditions.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )

    # Add map_id to cases — use batch mode for SQLite FK support
    with op.batch_alter_table('cases') as batch_op:
        batch_op.add_column(sa.Column('map_id', sa.String(length=36), nullable=True))
        batch_op.create_foreign_key('fk_cases_map_id', 'condition_maps', ['map_id'], ['id'])


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('runs', sa.Column('configuration_id', sa.VARCHAR(length=36), nullable=False))
    op.drop_constraint(None, 'runs', type_='foreignkey')
    op.create_foreign_key(None, 'runs', 'configurations', ['configuration_id'], ['id'])
    op.drop_column('runs', 'condition_id')
    op.drop_constraint(None, 'geometry_folders', type_='foreignkey')
    op.alter_column('geometry_folders', 'updated_at',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.alter_column('geometry_folders', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.alter_column('geometry_folders', 'created_by',
               existing_type=sa.VARCHAR(length=36),
               nullable=True)
    op.alter_column('geometry_folders', 'description',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=500),
               existing_nullable=True)
    op.drop_constraint(None, 'geometries', type_='foreignkey')
    op.drop_constraint(None, 'cases', type_='foreignkey')
    op.drop_column('cases', 'map_id')
    op.create_table('configurations',
    sa.Column('id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('case_id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('settings', sa.TEXT(), nullable=False),
    sa.Column('created_by', sa.VARCHAR(length=36), nullable=False),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_configurations_case_id'), 'configurations', ['case_id'], unique=False)
    op.drop_index(op.f('ix_conditions_map_id'), table_name='conditions')
    op.drop_table('conditions')
    op.drop_table('condition_maps')
    # ### end Alembic commands ###
