"""add_ride_height_yaw_to_conditions_and_systems_table

Revision ID: 8949ff1689b0
Revises: dfbd88e1bf8d
Create Date: 2026-04-21 16:54:26.070633

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8949ff1689b0'
down_revision: Union[str, Sequence[str], None] = 'dfbd88e1bf8d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('systems',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('source_geometry_id', sa.String(length=36), nullable=False),
    sa.Column('result_geometry_id', sa.String(length=36), nullable=True),
    sa.Column('condition_id', sa.String(length=36), nullable=True),
    sa.Column('transform_snapshot', sa.Text(), nullable=True),
    sa.Column('created_by', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['condition_id'], ['conditions.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['result_geometry_id'], ['geometries.id'], ),
    sa.ForeignKeyConstraint(['source_geometry_id'], ['geometries.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_systems_source_geometry_id'), 'systems', ['source_geometry_id'], unique=False)
    op.add_column('conditions', sa.Column('ride_height_json', sa.Text(), nullable=True))
    op.add_column('conditions', sa.Column('yaw_config_json', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('conditions', 'yaw_config_json')
    op.drop_column('conditions', 'ride_height_json')
    op.drop_index(op.f('ix_systems_source_geometry_id'), table_name='systems')
    op.drop_table('systems')
    # ### end Alembic commands ###
