"""add_stl_path_to_runs

Revision ID: ff0265eeeb01
Revises: abc6185bae8f
Create Date: 2026-04-21 19:47:54.111589

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ff0265eeeb01'
down_revision: Union[str, Sequence[str], None] = 'abc6185bae8f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('runs', sa.Column('stl_path', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('runs', 'stl_path')
    # ### end Alembic commands ###
